import { useEffect, useMemo, useRef, useState } from 'react';
import { BlockRegistry, can, fixtureBindings, runBlockLifecycle, workspaceMatches, type HostContext, type ProductRecipe, type Health } from './host';
import { fixtureBlock, affineBlock } from './blocks';
import { DefaultShell } from './shell';
import './style.css';

export const recipe: ProductRecipe = { name: 'Actionist', subtitle: 'Base workspace', tokens: { accent: '#7c5cff', canvas: '#f7f7fb' }, navigation: [{ id: 'workspace', label: 'Workspace', collapsible: false, items: [{ id: 'home', label: 'Overview', route: '/', icon: 'home' }, { id: 'knowledge', label: 'Knowledge', route: '/knowledge', icon: 'knowledge', blockId: 'actionist/affine-workspace', capability: 'knowledge.view' }, { id: 'fixture', label: 'Fixture block', route: '/fixture', icon: 'fixture', blockId: 'actionist/fixture', capability: 'fixture.view' }] }] };
export const registry = new BlockRegistry(); registry.register(fixtureBlock); registry.register(affineBlock(import.meta.env.VITE_AFFINE_MODULE_URL ?? ''));
const context: HostContext = { tenantId: 'tenant-demo', workspaceId: 'demo', principalId: 'fixture-user', principalKind: 'employee', teamIds: [], clientAccountIds: [], correlationId: 'fixture-run' };
const grants = { 'fixture-user': ['fixture.view', 'knowledge.view'] };
function Surface({ title, detail, kind }: { title: string; detail: string; kind: string }) { return <div data-verify={`state-${kind}`} className="surface"><div className="eyebrow">{kind}</div><h1>{title}</h1><p>{detail}</p></div>; }
export function App({ Shell = DefaultShell }: { Shell?: typeof DefaultShell }) { const [path, setPath] = useState(location.pathname.replace(/^\/w\/[^/]+/, '') || '/'); const [health, setHealth] = useState<Health>({ status: 'healthy' }); const unmountRef = useRef<(() => void | Promise<void>) | null>(null); const block = useMemo(() => registry.resolve(path), [path]); const pathWorkspace = location.pathname.match(/^\/w\/([^/]+)/)?.[1] ?? 'demo'; const allowed = !block || can(context, block.capability, grants); useEffect(() => { let disposed = false; const target = document.querySelector<HTMLElement>('[data-verify="block-mount"]'); if (!target || !block || !allowed || !workspaceMatches(pathWorkspace, context)) return; void runBlockLifecycle(block, target, context, fixtureBindings, h => !disposed && setHealth(h)).then(u => { if (!disposed) unmountRef.current = u; else void Promise.resolve(u()).catch(() => undefined); }).catch(error => { if (!disposed) { setHealth({ status: 'error', detail: error instanceof Error ? error.message : 'block failed' }); target.replaceChildren(); } }); return () => { disposed = true; const unmount = unmountRef.current; unmountRef.current = null; if (unmount) void Promise.resolve(unmount()).catch(() => undefined); target.replaceChildren(); }; }, [block, allowed, pathWorkspace]); const navigate = (route: string) => { const next = `/w/${context.workspaceId}${route === '/' ? '' : route}`; history.pushState({}, '', next); setPath(route); }; let body; if (pathWorkspace !== context.workspaceId) body = <Surface kind="denied" title="Workspace denied" detail="This session cannot open another workspace."/>; else if (block && !allowed) body = <Surface kind="denied" title="Access denied" detail="The host denies this capability by default."/>; else if (path === '/settings') body = <Surface kind="unavailable" title="Settings unavailable" detail="The fixture exposes the settings entry, but production settings storage is not installed."/>; else if (block) body = <><div data-verify="active-block" data-block-id={block.id} className="block-title"><span>{block.label}</span><span data-verify="health" data-health={health.status}>{health.status}</span></div><div data-verify="block-mount" />{health.status === 'unavailable' && <Surface kind="unavailable" title="Block unavailable" detail="This block is not configured in the fixture."/>}{health.status === 'error' && <Surface kind="error" title="Block error" detail={health.detail ?? 'The block failed to load.'}/>}</>; else body = <Surface kind="ready" title="Your workspace" detail="Choose a capability from the rail. Blocks mount into this canvas."/>; return <Shell recipe={recipe} active={path} onNavigate={navigate}>{body}</Shell>; }
