import { describe, expect, it } from 'vitest';
import { BlockRegistry, can, runBlockLifecycle, workspaceMatches, type RuntimeBindings } from './host';
import { affineBlock, fixtureBlock } from './blocks';

describe('host contracts', () => {
  const ctx = {tenantId:'t',workspaceId:'w',principalId:'p',principalKind:'employee' as const,teamIds:[],clientAccountIds:[],correlationId:'c'};
  const bindings: RuntimeBindings = {apiBaseUrl:'https://backend.test', identity:{issue:async()=> 'token'},data:{postgresSchema:'knowledge'},tokens:{resolve:()=>({})},ports:{emit:async()=>{},command:async()=>({ok:false})}};
  it('rejects route and id conflicts', () => { const r = new BlockRegistry(); r.register(fixtureBlock); expect(() => r.register({...fixtureBlock, id:'other'})).toThrow('route conflict'); expect(() => r.register(fixtureBlock)).toThrow('block conflict'); });
  it('denies capabilities by default and checks workspace ownership', () => { expect(can(ctx,'knowledge.view',{})).toBe(false); expect(workspaceMatches('other',ctx)).toBe(false); });
  it('runs preload before mount and invokes cleanup', async () => { const order:string[]=[]; const b = {...fixtureBlock, preload:async()=>{order.push('preload')}, mount:async(el:HTMLElement)=>{order.push('mount'); el.textContent='mounted'; return ()=>{order.push('unmount');}}}; const el=document.createElement('div'); const cleanup=await runBlockLifecycle(b,el,ctx,bindings,()=>{}); expect(order).toEqual(['preload','mount']); await cleanup(); expect(order).toEqual(['preload','mount','unmount']); });
  it('skips mount when health is unavailable', async () => { let mounted=false; const b={...fixtureBlock,health:async()=>({status:'unavailable' as const}),mount:async()=>{mounted=true;return ()=>{}}}; const el=document.createElement('div'); const cleanup=await runBlockLifecycle(b,el,ctx,bindings,()=>{}); await cleanup(); expect(mounted).toBe(false); });
  it('surfaces rejected module/import through lifecycle rejection', async () => { const b={...fixtureBlock,mount:async()=>{throw new Error('configured module failed')}}; await expect(runBlockLifecycle(b,document.createElement('div'),ctx,bindings,()=>{})).rejects.toThrow('configured module failed'); });
  it('reports missing AFFiNE configuration as unavailable', async () => { const b = affineBlock(); const missing = {...bindings,apiBaseUrl:''}; const h = await b.health?.(ctx, missing); expect(h?.status).toBe('unavailable'); const el = document.createElement('div'); const unmount = await b.mount(el, ctx, missing); expect(el.querySelector('[data-verify="block-unavailable"]')).toBeTruthy(); await unmount(); expect(el.childElementCount).toBe(0); });
  it('passes context and runtime bindings to a configured AFFiNE module', async () => { const seen:{context?:unknown;bindings?:unknown}={}; const url='data:text/javascript,'+encodeURIComponent('export async function mount(target, options){ globalThis.__seen=options; target.textContent="ok"; return ()=>{} }'); const b=affineBlock(url); const mod=await import(url); const el=document.createElement('div'); const cleanup=await b.mount(el,ctx,bindings); seen.context=(globalThis as {__seen?:{context?:unknown}}).__seen?.context; seen.bindings=(globalThis as {__seen?:{bindings?:unknown}}).__seen?.bindings; await cleanup(); expect(seen.context).toEqual(ctx); expect(seen.bindings).toMatchObject({apiBaseUrl:bindings.apiBaseUrl,data:bindings.data}); void mod; });
  it('fixture block cleans up its mount', async () => { const el = document.createElement('div'); const unmount = await fixtureBlock.mount(el, {} as never, {} as never); expect(el.querySelector('[data-verify="fixture-block"]')).toBeTruthy(); await unmount(); expect(el.childElementCount).toBe(0); });
});
