import { describe, expect, it } from 'vitest';
import { BlockRegistry, can, cleanupBlockMount, runBlockLifecycle, workspaceMatches, type RuntimeBindings } from './host';
import { affineBlock, fixtureBlock } from './blocks';

describe('host contracts', () => {
  const ctx = {tenantId:'t',workspaceId:'w',principalId:'p',principalKind:'employee' as const,teamIds:[],clientAccountIds:[],correlationId:'c'};
  const bindings: RuntimeBindings = {apiBaseUrl:'https://backend.test', identity:{issue:async()=> 'token'},data:{postgresSchema:'knowledge'},tokens:{resolve:()=>({})},ports:{emit:async()=>{},command:async()=>({ok:false})}};
  it('rejects route and id conflicts', () => { const r = new BlockRegistry(); r.register(fixtureBlock); expect(() => r.register({...fixtureBlock, id:'other'})).toThrow('route conflict'); expect(() => r.register(fixtureBlock)).toThrow('block conflict'); });
  it('denies capabilities by default and checks workspace ownership', () => { expect(can(ctx,'knowledge.view',{})).toBe(false); expect(workspaceMatches('other',ctx)).toBe(false); });
  it('runs preload before mount and invokes cleanup', async () => { const order:string[]=[]; const b = {...fixtureBlock, preload:async()=>{order.push('preload')}, mount:async(el:HTMLElement)=>{order.push('mount'); el.textContent='mounted'; return ()=>{order.push('unmount');}}}; const el=document.createElement('div'); const cleanup=await runBlockLifecycle(b,el,ctx,bindings,()=>{}); expect(order).toEqual(['preload','mount']); await cleanup(); expect(order).toEqual(['preload','mount','unmount']); });
  it('does not mount a lifecycle run that becomes stale before mount', async () => { let active = true; let mounted = false; const b = {...fixtureBlock, preload:async()=>{active = false}, mount:async()=>{mounted = true; return ()=>{}}}; await runBlockLifecycle(b,document.createElement('div'),ctx,bindings,()=>{},()=>active); expect(mounted).toBe(false); });
  it('skips mount when health is unavailable', async () => { let mounted=false; const b={...fixtureBlock,health:async()=>({status:'unavailable' as const}),mount:async()=>{mounted=true;return ()=>{}}}; const el=document.createElement('div'); const cleanup=await runBlockLifecycle(b,el,ctx,bindings,()=>{}); await cleanup(); expect(mounted).toBe(false); });
  it('surfaces rejected module/import through lifecycle rejection', async () => { const b={...fixtureBlock,mount:async()=>{throw new Error('configured module failed')}}; await expect(runBlockLifecycle(b,document.createElement('div'),ctx,bindings,()=>{})).rejects.toThrow('configured module failed'); });
  it('reports missing AFFiNE configuration as unavailable', async () => { const b = affineBlock({ moduleUrl: '/missing.js', backendBase: '/backend', issuerUrl: '/issuer', expectedClientId: 'bykonz-yard' }); const originalFetch=globalThis.fetch; globalThis.fetch=async()=>new Response('',{status:503}); const h = await b.health?.(ctx, bindings); expect(h?.status).toBe('unavailable'); globalThis.fetch=originalFetch; });
  it('rejects a backend session that does not match the issuer identity', async () => { const originalFetch=globalThis.fetch; globalThis.fetch=async input => String(input).includes('knowledge-context') ? new Response(JSON.stringify({userId:'p',email:'p@example.test',clientId:'bykonz-yard',workspaceId:'w',expiresAt:new Date(Date.now()+60000).toISOString(),capabilities:['view','edit'],token:'signed'}),{status:200}) : new Response(JSON.stringify({user:{id:'other'}}),{status:200}); const h = await affineBlock({moduleUrl:'/module.js',backendBase:'/backend',issuerUrl:'/issuer',expectedClientId:'bykonz-yard'}).health?.(ctx, bindings); expect(h).toEqual({status:'unavailable',detail:'Knowledge backend session mismatch'}); globalThis.fetch=originalFetch; });
  it('rejects a backend workspace read-back that does not match the issuer identity', async () => { const originalFetch=globalThis.fetch; globalThis.fetch=async input => { const url=String(input); if (url.includes('knowledge-context')) return new Response(JSON.stringify({userId:'p',email:'p@example.test',clientId:'bykonz-yard',workspaceId:'w',expiresAt:new Date(Date.now()+60000).toISOString(),capabilities:['view','edit'],token:'signed'}),{status:200}); if (url.includes('/api/auth/session')) return new Response(JSON.stringify({user:{id:'p'}}),{status:200}); return new Response(JSON.stringify({data:{currentUser:{id:'p'},workspace:{id:'other'}}}),{status:200}); }; const h = await affineBlock({moduleUrl:'/module.js',backendBase:'/backend',issuerUrl:'/issuer',expectedClientId:'bykonz-yard'}).health?.(ctx, bindings); expect(h).toEqual({status:'unavailable',detail:'Knowledge backend workspace session mismatch'}); globalThis.fetch=originalFetch; });
  it('passes context and runtime bindings to a configured AFFiNE module', async () => { const originalFetch=globalThis.fetch; globalThis.fetch=async(input)=>String(input).includes('knowledge-context') ? new Response(JSON.stringify({userId:'p',email:'p@example.test',clientId:'bykonz-yard',workspaceId:'w',expiresAt:new Date(Date.now()+60000).toISOString(),capabilities:['view','edit'],token:'signed'}),{status:200}) : new Response('{}',{status:200}); const seen:{options?:unknown}={}; const url='data:text/javascript,'+encodeURIComponent('export async function mount(target, options){ globalThis.__seen=options; target.textContent="ok"; return ()=>{} }'); const b=affineBlock({moduleUrl:url,backendBase:'https://backend.test',issuerUrl:'/issuer',expectedClientId:'bykonz-yard'}); const el=document.createElement('div'); const cleanup=await b.mount(el,ctx,bindings); seen.options=(globalThis as {__seen?:unknown}).__seen; await cleanup(); expect(seen.options).toMatchObject({host:{identity:{workspaceId:'w'},database:{config:{schema:'knowledge'}},tokens:{sisoRequestContext:'signed'}},context:ctx,backendBase:'https://backend.test'}); globalThis.fetch=originalFetch; });
  it('waits for donor unmount before clearing its DOM', async () => { const order:string[]=[]; const el=document.createElement('div'); el.innerHTML='<div>mounted</div>'; await cleanupBlockMount(el, async()=>{ order.push(`unmount:${el.childElementCount}`); }); order.push(`cleared:${el.childElementCount}`); expect(order).toEqual(['unmount:1','cleared:0']); });
  it('fixture block cleans up its mount', async () => { const el = document.createElement('div'); const unmount = await fixtureBlock.mount(el, {} as never, {} as never); expect(el.querySelector('[data-verify="fixture-block"]')).toBeTruthy(); await unmount(); expect(el.childElementCount).toBe(0); });
});
